In [1]:
import numpy as np
import torch

In [2]:
SEED = 143

In [3]:
np.random.seed(SEED)
torch.manual_seed(SEED)

In [8]:
# create a random tensor

x = torch.rand(2,3)
print(f"x: {x}")
print(f"x shape: {x.shape}")
print(f"x type: {x.type()}")

x: tensor([[0.8208, 0.6275, 0.0617],
        [0.9273, 0.4820, 0.6807]])
x shape: torch.Size([2, 3])
x type: torch.FloatTensor


In [10]:
x = torch.zeros(2,4)
print(x)
x = torch.ones(5,2)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [11]:
x = torch.tensor([[1,2,3], [4,5,6]])
print(f"x: {x}")
print(f"x shape: {x.shape}")
print(f"x type: {x.type()}")

x: tensor([[1, 2, 3],
        [4, 5, 6]])
x shape: torch.Size([2, 3])
x type: torch.LongTensor


In [12]:
x = torch.tensor(np.random.rand(4,5))
print(f"x: {x}")
print(f"x shape: {x.shape}")
print(f"x type: {x.type()}")

x: tensor([[0.7378, 0.3400, 0.4681, 0.4239, 0.5683],
        [0.8813, 0.0331, 0.0088, 0.1992, 0.1673],
        [0.9690, 0.0566, 0.0896, 0.2796, 0.6093],
        [0.0706, 0.5725, 0.3325, 0.2617, 0.0926]], dtype=torch.float64)
x shape: torch.Size([4, 5])
x type: torch.DoubleTensor


In [17]:
x = torch.Tensor(3,4)
print(f"x: {x}")
print(f"x shape: {x.shape}")
print(f"x type: {x.type()}")

x = x.long()
print(f"x: {x}")
print(f"x shape: {x.shape}")
print(f"x type: {x.type()}")


x: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
x shape: torch.Size([3, 4])
x type: torch.FloatTensor
x: tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
x shape: torch.Size([3, 4])
x type: torch.LongTensor


In [18]:
# Operations

x = torch.randn(2,3)
y = torch.randn(2,3)

z = x + y

print(f"x: {z}")
print(f"x shape: {z.shape}")
print(f"x type: {z.type()}")


x: tensor([[-0.4352, -0.2858, -0.1944],
        [-0.8054, -0.0948,  0.5615]])
x shape: torch.Size([2, 3])
x type: torch.FloatTensor


In [19]:
# Dot Product

x = torch.randn(2,3)
y = torch.randn(3, 2)

z = torch.mm(x, y)

print(f"x: {z}")
print(f"x shape: {z.shape}")
print(f"x type: {z.type()}")


x: tensor([[ 0.6433, -0.8048],
        [ 0.8759,  0.5991]])
x shape: torch.Size([2, 2])
x type: torch.FloatTensor


In [20]:
# Operations

x = torch.randn(2,3)
y = torch.randn(2,3)

z = x + y

print(f"x: {z}")
print(f"x shape: {z.shape}")


z_t = torch.t(z)

print(f"x: {z_t}")
print(f"x shape: {z_t.shape}")


x: tensor([[ 0.1247,  0.4715,  0.7204],
        [-1.4261,  2.5406, -0.2744]])
x shape: torch.Size([2, 3])
x: tensor([[ 0.1247, -1.4261],
        [ 0.4715,  2.5406],
        [ 0.7204, -0.2744]])
x shape: torch.Size([3, 2])


In [21]:
# Reshape

# Operations

x = torch.randn(2,3)

print(f"x: {x}")
print(f"x shape: {x.shape}")

z = x.view(3, 2)

print(f"x: {z}")
print(f"x shape: {z.shape}")

x: tensor([[ 1.0961, -0.2525, -0.3476],
        [ 0.2405,  0.8378,  0.2531]])
x shape: torch.Size([2, 3])
x: tensor([[ 1.0961, -0.2525],
        [-0.3476,  0.2405],
        [ 0.8378,  0.2531]])
x shape: torch.Size([3, 2])


In [23]:
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print(f"Size: {x.shape}")
print(f"x: \n{x}\n")

a = x.view(x.size(1), -1)
print(f"\nSize: {a.shape}")
print(f"a: \n{a}\n")

b = x.transpose(0,1).contiguous()
print(f"\nSize: {b.shape}")
print(f"b: \n{b}\n")

c = b.view(b.size(0), -1)
print(f"\nSize: {c.shape}")
print(f"c: \n{c}")

Size: torch.Size([2, 3, 4])
x: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
a: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])


Size: torch.Size([3, 2, 4])
b: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
c: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [25]:
# Dimensional operation

x = torch.randn(2,3)

print(torch.sum(x, dim=0)) # sum by rows
print(torch.sum(x, dim=1)) #sum by columns

tensor([ 1.2245, -2.6104,  0.5606])
tensor([ 1.5975, -2.4228])


In [35]:
# Indexing

x = torch.randn(4,7)
print(x)

print(f"x[:1] {x[:1]}")

print(f"x[:3, 4:6] {x[:3, 4:6]}")

tensor([[ 1.8475, -0.4165, -0.6878,  0.4896,  0.1208, -0.1288,  0.5506],
        [ 0.5848,  0.7463, -0.3194, -1.6351,  0.9498,  0.5226,  0.8096],
        [-0.2982, -1.1556, -0.1704, -0.2624, -1.6847, -0.7612, -0.5449],
        [-0.5667,  0.2012, -0.3032,  1.2812, -1.4127, -0.1953,  0.5376]])
x[:1] tensor([[ 1.8475, -0.4165, -0.6878,  0.4896,  0.1208, -0.1288,  0.5506]])
x[:3, 4:6] tensor([[ 0.1208, -0.1288],
        [ 0.9498,  0.5226],
        [-1.6847, -0.7612]])


In [44]:
# slicing

x = torch.randn(4,7)
print(f"x = {x}")

col_indices = torch.LongTensor([0,2])
chosen = torch.index_select(x, dim=1, index=col_indices)
print(f"sliced values:\n {chosen}")


row_indices = torch.LongTensor([0,2])
col_indices = torch.LongTensor([3,6])
chosen = x[row_indices, col_indices]
print(f"sliced values:\n {chosen}")

x = tensor([[ 1.4758, -0.2786, -1.8662, -0.1659, -0.8642,  1.4845, -1.3522],
        [ 1.4226,  1.9030,  0.4085,  0.8041, -0.2803,  1.6250,  0.4153],
        [ 0.2785, -1.0900, -0.6049, -1.8552, -1.1751, -0.3588, -0.3266],
        [-0.5079,  1.0423, -2.0301,  0.1769,  0.2982,  4.1695,  1.1074]])
sliced values:
 tensor([[ 1.4758, -1.8662],
        [ 1.4226,  0.4085],
        [ 0.2785, -0.6049],
        [-0.5079, -2.0301]])
sliced values:
 tensor([-0.1659, -0.3266])


In [46]:
# Contat

x = torch.randn(4,2)

print(torch.cat([x,x], dim=0))
print(torch.cat([x,x], dim=1))

tensor([[ 0.8909, -0.7094],
        [ 0.2914,  1.1309],
        [ 0.0885, -2.1020],
        [ 0.9740, -0.9215],
        [ 0.8909, -0.7094],
        [ 0.2914,  1.1309],
        [ 0.0885, -2.1020],
        [ 0.9740, -0.9215]])
tensor([[ 0.8909, -0.7094,  0.8909, -0.7094],
        [ 0.2914,  1.1309,  0.2914,  1.1309],
        [ 0.0885, -2.1020,  0.0885, -2.1020],
        [ 0.9740, -0.9215,  0.9740, -0.9215]])


In [48]:
# stack

x = torch.randn(4,2)

print(torch.stack([x,x], dim=0))
print(torch.stack([x,x], dim=0).shape)


tensor([[[-0.2837, -0.4087],
         [ 0.3731,  2.4777],
         [ 0.3829,  0.9551],
         [ 1.4261, -0.4581]],

        [[-0.2837, -0.4087],
         [ 0.3731,  2.4777],
         [ 0.3829,  0.9551],
         [ 1.4261, -0.4581]]])
torch.Size([2, 4, 2])


In [50]:
# Gradient

x = torch.rand(3,4, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward()
print(x)
print(x.grad)

tensor([[0.0227, 0.9779, 0.0246, 0.0306],
        [0.3812, 0.8859, 0.2566, 0.0388],
        [0.2013, 0.2942, 0.2942, 0.4623]], requires_grad=True)
tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


In [51]:
# CUDA
print(torch.cuda.is_available())

True


In [52]:
# set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda
