In [1]:
import numpy as np

In [2]:
np.random.seed(145)

In [6]:
x = np.array(6)
print(f"x: {x}")
print(f"x no. of dimensions: {x.ndim}")
print(f"x shape: {x.shape}")
print(f"x size: {x.size}")
print(f"x data type: {x.dtype}")

x: 6
x no. of dimensions: 0
x shape: ()
x size: 1
x data type: int32


In [8]:
x = np.array([1.3, 4.0, 3.7, 22.14])
print(f"x: {x}")
print(f"x no. of dimensions: {x.ndim}")
print(f"x shape: {x.shape}")
print(f"x size: {x.size}")
print(f"x data type: {x.dtype}")

x: [ 1.3   4.    3.7  22.14]
x no. of dimensions: 1
x shape: (4,)
x size: 4
x data type: float64


In [10]:
x = np.array([[1.3, 4.0], [3.7, 22.14]])
print(f"x: {x}")
print(f"x no. of dimensions: {x.ndim}")
print(f"x shape: {x.shape}")
print(f"x size: {x.size}")
print(f"x data type: {x.dtype}")

x: [[ 1.3   4.  ]
 [ 3.7  22.14]]
x no. of dimensions: 2
x shape: (2, 2)
x size: 4
x data type: float64


In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.random((3,5))

array([[0.28304195, 0.0020298 , 0.53057896, 0.08036104, 0.65225755],
       [0.77073903, 0.59813958, 0.32668356, 0.69757615, 0.49534452],
       [0.94822338, 0.57269538, 0.17417718, 0.09219379, 0.06841918]])

In [20]:
np.random.randint((2,5))

array([0, 4])

In [22]:
np.random.random_integers(5)

C:\Users\majumder\AppData\Local\Temp\ipykernel_6996\339360557.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  np.random.random_integers(5)


3

In [25]:
# Indexing

x = np.array([[1.3, 4.0], [3.7, 22.14]])
print(x[1][0])
x[0][1]=2.11
print(x)

3.7
[[ 1.3   2.11]
 [ 3.7  22.14]]


In [27]:
# Slicing

x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (x)

x[:2]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])