In [2]:
import numpy as np

In [3]:
np.random.seed(145)

In [4]:
x = np.array(6)
print(f"x: {x}")
print(f"x no. of dimensions: {x.ndim}")
print(f"x shape: {x.shape}")
print(f"x size: {x.size}")
print(f"x data type: {x.dtype}")

x: 6
x no. of dimensions: 0
x shape: ()
x size: 1
x data type: int32


In [5]:
x = np.array([1.3, 4.0, 3.7, 22.14])
print(f"x: {x}")
print(f"x no. of dimensions: {x.ndim}")
print(f"x shape: {x.shape}")
print(f"x size: {x.size}")
print(f"x data type: {x.dtype}")

x: [ 1.3   4.    3.7  22.14]
x no. of dimensions: 1
x shape: (4,)
x size: 4
x data type: float64


In [6]:
x = np.array([[1.3, 4.0], [3.7, 22.14]])
print(f"x: {x}")
print(f"x no. of dimensions: {x.ndim}")
print(f"x shape: {x.shape}")
print(f"x size: {x.size}")
print(f"x data type: {x.dtype}")

x: [[ 1.3   4.  ]
 [ 3.7  22.14]]
x no. of dimensions: 2
x shape: (2, 2)
x size: 4
x data type: float64


In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.random((3,5))

array([[0.28304195, 0.0020298 , 0.53057896, 0.08036104, 0.65225755],
       [0.77073903, 0.59813958, 0.32668356, 0.69757615, 0.49534452],
       [0.94822338, 0.57269538, 0.17417718, 0.09219379, 0.06841918]])

In [11]:
np.random.randint((2,5))

array([0, 4])

In [12]:
np.random.random_integers(5)

C:\Users\majumder\AppData\Local\Temp\ipykernel_16188\339360557.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  np.random.random_integers(5)


3

In [13]:
# Indexing

x = np.array([[1.3, 4.0], [3.7, 22.14]])
print(x[1][0])
x[0][1]=2.11
print(x)

3.7
[[ 1.3   2.11]
 [ 3.7  22.14]]


In [14]:
# Slicing

x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (x)

x[:2]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
# Indexing
print(x)
rows = [1, 2, 0]
cols = [3, 0, 1]

print(f"rows: {rows}")
print(f"cols: {cols}")

print(f"indexed values: {x[rows, cols]}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows: [1, 2, 0]
cols: [3, 0, 1]
indexed values: [8 9 2]


In [16]:
# Boolean Indexing

print(x[x>5])
print(x>2)

[ 6  7  8  9 10 11 12]
[[False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [17]:
# Arithmetic

x = np.array([[1.3, 2.2], [5.76, 6.121]], dtype=np.float64)
y = np.array([[3.1, 4.72], [4.32, 5.541]], dtype=np.float64)

print(f"add: {np.add(x, y)}")

add: [[ 4.4    6.92 ]
 [10.08  11.662]]


In [18]:
# Dot product

x = np.array([[1.3, 2.2], [5.76, 6.121]], dtype=np.float64)
y = np.array([[3.1, 4.72], [4.32, 5.541]], dtype=np.float64)

z = np.dot(x, y)

print(f"{x.shape} * {y.shape} = {z.shape}")
print(z)

(2, 2) * (2, 2) = (2, 2)
[[13.534    18.3262  ]
 [44.29872  61.103661]]


In [19]:
# Axis Operations

x = np.array([[1, 2], 
             [4, 5]])
print(x)
print(f"Sum of all elements: {np.sum(x)}")
print(f"Sum of all elements across rows: {np.sum(x, axis=0)}")
print(f"Sum of all elements across columns: {np.sum(x, axis=1)}")

[[1 2]
 [4 5]]
Sum of all elements: 12
Sum of all elements across rows: [5 7]
Sum of all elements across columns: [3 9]


In [20]:
# Min/ Max

x = np.array([[1, 2, 3],
             [4, 5, 6]])
print(x)

print(f"Minimum of all elements: {np.min(x)}")
print(f"Maximum of all elements: {np.max(x)}")

print(f"Minimum of all elements across rows: {np.min(x, axis=0)}")
print(f"Maximum of all elements across rows: {np.max(x, axis=0)}")

print(f"Minimum of all elements across columns: {np.min(x, axis=1)}")
print(f"Maximum of all elements across columns: {np.max(x, axis=1)}")

[[1 2 3]
 [4 5 6]]
Minimum of all elements: 1
Maximum of all elements: 6
Minimum of all elements across rows: [1 2 3]
Maximum of all elements across rows: [4 5 6]
Minimum of all elements across columns: [1 4]
Maximum of all elements across columns: [3 6]


In [21]:
# Broadcast

x = np.array([19, 9])
y = np.array(2)

z = x + y

print(f"Broadcast: {z}")

Broadcast: [21 11]


In [22]:
a = np.array([2,3,4])
b = np.expand_dims(a, axis=1)
c = a + b
print(c)
print(f"Shape a: {a.shape}, Shape b: {b.shape}, Shape c: {c.shape}")
print(f"Shape a: {a.reshape(-1,1).shape}")

[[4 5 6]
 [5 6 7]
 [6 7 8]]
Shape a: (3,), Shape b: (3, 1), Shape c: (3, 3)
Shape a: (3, 1)


In [26]:
# Transpose

x = np.array([[1,2,3], [4,5,6]])
print(f"x shape: {x.shape}")
y = np.transpose(x, (1,0))
print(f"y shape: {y.shape}")

x shape: (2, 3)
y shape: (3, 2)


In [28]:
x = np.array([1,2,3,4,5,6])
print(f"x shape: {x.shape}")
y= np.reshape(x, (2,3))
print(f"y shape: {y.shape}")
z= np.reshape(x, (-1,2))
print(f"z shape: {z.shape}")

x shape: (6,)
y shape: (2, 3)
z shape: (3, 2)


In [29]:
# Concatenation
x = np.array([[1,2,3], [4,5,6]])
print(f"x shape: {x.shape}")

y = np.concatenate((x,x), axis=0)
print(y)

z = np.concatenate((x,x), axis=1)
print(z)

x shape: (2, 3)
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [33]:
# Stacking
x = np.array([[1,2,3], [4,5,6]])
print(f"x shape: {x.shape}")

y = np.stack((x,x), axis=0)
print(y)
print(y.shape)

z = np.stack((x,x), axis=1)
print(z)
print(z.shape)

x shape: (2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]]
(2, 2, 3)


In [47]:
# Expandinga & reducing

x = np.array([[1,2,3], [4,5,6]])
print(x.shape)
y = np.expand_dims(x,1)
print(y.shape)
z = np.squeeze(y,1)
print(z.shape)


(2, 3)
(2, 1, 3)
(2, 3)
